import PublicLayout from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";
import { Github, Linkedin, Mail, MapPin, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";

export default function Contact() {
  const { language } = useLanguage();
  const fr = language === "fr";
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [message, setMessage] = useState("");
  const send = trpc.contact.submit.useMutation({ onSuccess: () => { toast.success(fr ? "Votre message a bien été envoyé." : "Your message was sent successfully."); setName(""); setEmail(""); setMessage(""); }, onError: () => toast.error(fr ? "Impossible d’envoyer le message pour le moment." : "Unable to send the message right now.") });
  const submit = (event: FormEvent) => { event.preventDefault(); send.mutate({ name, email, message }); };
  return <PublicLayout><section className="contact-page"><div className="contact-intro"><div className="eyebrow"><Mail size={14} /> {fr ? "Prise de contact" : "Get in touch"}</div><h1>{fr ? "Un service backend" : "A backend service"}<br /><em>{fr ? "à fiabiliser ?" : "to make reliable?"}</em></h1><p>{fr ? "Déploiement à automatiser, API à concevoir ou infrastructure à clarifier : décrivez le contexte et les contraintes techniques." : "A deployment to automate, an API to design or infrastructure to clarify: share the context and technical constraints."}</p><div className="contact-direct"><a href="mailto:liolisena@gmail.com"><Mail size={18} /> liolisena@gmail.com</a><span><MapPin size={18} /> Bénin</span><a href="https://linkedin.com/in/lionellite" target="_blank" rel="noreferrer"><Linkedin size={18} /> LinkedIn</a><a href="https://github.com/lionellite" target="_blank" rel="noreferrer"><Github size={18} /> GitHub</a></div></div><form className="contact-form" onSubmit={submit}><div className="form-label">{fr ? "Décrivez le contexte" : "Describe the context"}</div><label>{fr ? "Votre nom" : "Your name"}<input required minLength={2} maxLength={160} value={name} onChange={e => setName(e.target.value)} placeholder={fr ? "Prénom et nom" : "First and last name"} /></label><label>{fr ? "Votre e-mail" : "Your email"}<input required type="email" maxLength={320} value={email} onChange={e => setEmail(e.target.value)} placeholder={fr ? "vous@entreprise.com" : "you@company.com"} /></label><label>{fr ? "Votre message" : "Your message"}<textarea required minLength={10} maxLength={5000} value={message} onChange={e => setMessage(e.target.value)} placeholder={fr ? "Architecture actuelle, besoin, délais ou contraintes à considérer…" : "Current architecture, needs, timelines or constraints to consider…"} rows={6} /></label><button className="send-button" type="submit" disabled={send.isPending}>{send.isPending ? (fr ? "Envoi en cours…" : "Sending…") : <>{fr ? "Envoyer le message" : "Send the message"} <Send size={17} /></>}</button><p className="form-note">{fr ? "Le message est enregistré et transmis à Lionel par e-mail." : "The message is saved and forwarded to Lionel by email."}</p></form></section></PublicLayout>;
}
