import PublicLayout from "@/components/PublicLayout";
import ProjectSignal from "@/components/ProjectSignal";
import SystemScene from "@/components/SystemScene";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowDownRight, ArrowUpRight, ChevronDown, Cpu, Database, Github, GitBranch, GraduationCap, Linkedin, LockKeyhole, Mail, MapPin, ServerCog, TerminalSquare } from "lucide-react";
import { Link } from "wouter";

function IdentityModule({ imageUrl, name }: { imageUrl?: string | null; name: string }) {
  return <div className="terminal-identity terminal-identity--scene"><div className="terminal-identity__head"><span>TOPOLOGY_MODULE</span><span>LIVE_RENDER</span></div><SystemScene /><div className="terminal-identity__operator">{imageUrl ? <img src={imageUrl} alt={`Portrait de ${name}`} /> : <span>LA</span>}<div><strong>OPERATOR: {name.toUpperCase()}</strong><small>NODE: BENIN / WEST_AFRICA</small></div></div><div className="terminal-identity__foot"><span>NETWORK: RELAYED</span><span>ENCRYPTION: ON</span></div></div>;
}

export default function Home() {
  const { data, isLoading, isError } = trpc.portfolio.get.useQuery();
  const { data: projects } = trpc.projects.list.useQuery();
  const profile = data?.profile;
  const featured = projects?.filter(project => project.isFeatured).slice(0, 2) ?? [];
  const skillGroups = (data?.skills ?? []).reduce<Record<string, { id: number; name: string }[]>>((groups, skill) => { (groups[skill.category] ??= []).push({ id: skill.id, name: skill.name }); return groups; }, {});
  return <PublicLayout><div className="terminal-home">
    <section className="terminal-hero">
      <div className="terminal-hero__rail"><span>00</span><i /><span>01</span><i /><span>02</span></div>
      <div className="terminal-hero__copy"><p className="terminal-prompt">lionel@systems:~$ cat profile.yml</p><p className="terminal-overline"><span className="terminal-pulse" /> BACKEND / INFRASTRUCTURE / DEVOPS</p><h1>J’assemble<br />des <em>systèmes</em><br />qui tiennent.</h1><p className="terminal-hero__text">{isError ? "Le profil est temporairement indisponible. Le canal de contact reste ouvert." : profile?.bio ?? "Développeur Backend Python, orienté systèmes Linux, infrastructure et déploiements fiables."}</p><div className="terminal-actions"><Link href="/projets" className="terminal-button terminal-button--signal"><span>EXPLORE</span> systems <ArrowUpRight size={16} /></Link><a href="mailto:liolisena@gmail.com" className="terminal-button">open_channel <Mail size={16} /></a></div></div>
      <div className="terminal-hero__module"><IdentityModule imageUrl={profile?.photoUrl} name={profile?.fullName ?? "Lionel Adoukonou"} /><div className="terminal-runtime"><div><Activity size={16} /><span>UPTIME</span><strong>99.9%</strong></div><div><ServerCog size={16} /><span>STACK</span><strong>PY / LINUX</strong></div><div><MapPin size={16} /><span>ZONE</span><strong>{profile?.location ?? "BENIN"}</strong></div></div></div>
      <div className="terminal-hero__status"><span><i className="terminal-pulse" /> {profile?.availability ?? "OPEN_FOR_COLLABORATION"}</span><a href="#systems">SCROLL_TO_SYSTEMS <ChevronDown size={15} /></a></div>
    </section>

    <section className="terminal-brief" id="parcours"><header><p className="terminal-prompt">$ whoami --focus</p><h2>De l’API au déploiement,<br /><em>je traite l’ensemble du flux.</em></h2></header><div className="terminal-brief__grid"><article><span>01 / PRINCIPLE</span><p>Concevoir des blocs simples, observables et faciles à maintenir.</p></article><article><span>02 / SCOPE</span><p>Backend Python, automatisation, systèmes Linux et services Cloud.</p></article><article><span>03 / METHOD</span><p>Comprendre la contrainte avant de choisir le bon niveau de complexité.</p></article></div></section>

    <section className="terminal-protocol"><div className="terminal-section-heading"><div><p className="terminal-prompt">$ trace --path delivery</p><h2>Le protocole<br /><em>de livraison.</em></h2></div><p>Un système utile commence par un contexte explicite, transite par une architecture compréhensible et se termine par une exploitation prévisible.</p></div><div className="terminal-protocol__grid"><article><header><span>NODE.01</span><TerminalSquare size={17} /></header><h3>Contraintes</h3><p>Clarifier les utilisateurs, les flux, les données et les risques avant d’écrire la première interface.</p><small>INPUT / CONTEXT / SCOPE</small></article><article><header><span>NODE.02</span><Database size={17} /></header><h3>Architecture</h3><p>Découper le service, choisir les bons contrats et rendre la donnée observable dès la conception.</p><small>API / DATA / EVENTS</small></article><article><header><span>NODE.03</span><ServerCog size={17} /></header><h3>Exploitation</h3><p>Préparer le déploiement, les retours d’erreur et les évolutions au moment où le produit prend de l’ampleur.</p><small>DEPLOY / LOGS / ITERATE</small></article></div><footer className="terminal-protocol__foot"><span><i /> ROUTE: INPUT → SERVICE → OPERATIONS</span><span>MODE: COLLABORATIVE_ENGINEERING</span></footer></section>

    <section className="terminal-capabilities"><div className="terminal-section-heading"><div><p className="terminal-prompt">$ ls ./capabilities</p><h2>Modules<br />chargés.</h2></div><p>Une base technique construite pour rendre les produits lisibles, opérables et évolutifs.</p></div><div className="terminal-capabilities__grid">{isLoading ? <div className="terminal-loader"><span /><span /><span /><span /></div> : Object.entries(skillGroups).map(([category, skills], index) => <article key={category}><div><span>MOD.{String(index + 1).padStart(2, "0")}</span><Cpu size={16} /></div><h3>{category}</h3><p>{skills.map(skill => skill.name).join(" / ")}</p></article>)}</div></section>

    <section className="terminal-systems" id="systems"><div className="terminal-section-heading terminal-section-heading--dark"><div><p className="terminal-prompt">$ systemctl list-units --active</p><h2>Systèmes<br /><em>en vitrine.</em></h2></div><Link href="/projets" className="terminal-link">VIEW_ALL_SYSTEMS <ArrowUpRight size={16} /></Link></div><div className="terminal-systems__grid">{isLoading ? <div className="terminal-loader terminal-loader--dark"><span /><span /></div> : featured.map((project, index) => <article key={project.id}><Link href={`/projets/${project.slug}`} className="terminal-system-card">{project.coverImageUrl ? <img src={project.coverImageUrl} alt="" /> : <ProjectSignal title={project.title} index={index} />}</Link><div className="terminal-system-card__meta"><div><span>SYS.{String(index + 1).padStart(2, "0")}</span><h3>{project.title}</h3><p>{project.shortDescription}</p></div><Link href={`/projets/${project.slug}`} aria-label={`Voir ${project.title}`}><ArrowUpRight size={18} /></Link></div></article>)}</div></section>

    <section className="terminal-evidence"><div className="terminal-evidence__intro"><p className="terminal-prompt">$ cat ./proof-of-work.json</p><h2>Des systèmes<br />documentés,<br /><em>pas des promesses.</em></h2></div><div className="terminal-evidence__grid"><article><strong>{projects?.length ?? "—"}</strong><div><span>SYSTEM_RECORDS</span><p>Projets publiés avec leur rôle, leur stack et leur contexte.</p></div></article><article><strong>{Object.keys(skillGroups).length || "—"}</strong><div><span>CAPABILITY_DOMAINS</span><p>Domaines techniques activés par le parcours et les réalisations.</p></div></article><article><strong>{data?.experiences.length ?? "—"}</strong><div><span>EXECUTION_ENTRIES</span><p>Expériences qui structurent la manière de concevoir et déployer.</p></div></article></div></section>

    <section className="terminal-log"><div className="terminal-log__intro"><p className="terminal-prompt">$ tail -f ./career.log</p><h2>Journal<br />d’exécution.</h2><p>Une trajectoire centrée sur la pratique, l’apprentissage et la transmission.</p></div><div className="terminal-log__entries">{isLoading ? <div className="terminal-loader"><span /><span /><span /></div> : data?.experiences.map((experience, index) => <article key={experience.id}><span>{experience.startDate}</span><div><p>ENTRY_{String(index + 1).padStart(2, "0")}</p><h3>{experience.title}</h3><small>{experience.organization}{experience.location ? ` · ${experience.location}` : ""}</small><p>{experience.description}</p></div><GitBranch size={16} /></article>)}</div><div className="terminal-education"><div><GraduationCap size={17} /><span>ACADEMIC_DATA</span></div>{data?.educations.slice(0, 3).map(education => <p key={education.id}><strong>{education.credential}</strong><span>{education.institution} / {education.endDate ?? "CURRENT"}</span></p>)}</div></section>

    <section className="terminal-cta"><div className="terminal-cta__icon"><LockKeyhole size={20} /></div><p className="terminal-prompt">$ init collaboration --secure</p><h2>Un système à clarifier ?</h2><p>API, automatisation, déploiement ou infrastructure : décrivez le contexte et les contraintes, puis ouvrons le bon canal.</p><Link href="/contact" className="terminal-button terminal-button--signal">START_SESSION <ArrowDownRight size={16} /></Link><div><a href="https://github.com/lionellite" target="_blank" rel="noreferrer" aria-label="Profil GitHub de Lionel"><Github size={16} /></a><a href="https://linkedin.com/in/lionellite" target="_blank" rel="noreferrer" aria-label="Profil LinkedIn de Lionel"><Linkedin size={16} /></a><a href="mailto:liolisena@gmail.com" aria-label="Écrire à Lionel"><Mail size={16} /></a></div></section>
  </div></PublicLayout>;
}
